export const enum PrecalculateKey {
   CALCULATED = '__mc_calculated',
   SECOND_TIME = '__mc_secondtime',
   BEAT_TIME = '__mc_beattime',
   DURATION_SECOND_TIME = '__mc_duration_secondtime',
   DURATION_BEAT_TIME = '__mc_duration_beattime',
   TAIL_SECOND_TIME = '__mc_tail_secondtime',
   TAIL_BEAT_TIME = '__mc_tail_beattime',
   POSITION = '__mc_position',
   TAIL_POSITION = '__mc_tail_position',
   ANGLE = '__mc_angle',
   TAIL_ANGLE = '__mc_tail_angle',
   SNAPPED = '__mc_snapped',
   COLOR = '__mc_color',
}
