export const enum PrecalculateKey {
   CALCULATED = '__mc_calc',
   SECOND_TIME = '__mc_st',
   BEAT_TIME = '__mc_bt',
   DURATION_SECOND_TIME = '__mc_dst',
   DURATION_BEAT_TIME = '__mc_dbt',
   TAIL_SECOND_TIME = '__mc_tst',
   TAIL_BEAT_TIME = '__mc_tbt',
   POSITION = '__mc_p',
   TAIL_POSITION = '__mc_tp',
   ANGLE = '__mc_a',
   TAIL_ANGLE = '__mc_ta',
   SNAPPED = '__mc_s',
   COLOR = '__mc_color',
   BEZIER_PATH = '__mc_bp',
   HEAD_NOTES = '__mc_hn',
   TAIL_NOTES = '__mc_tn',
   CHAIN_LINKS = '__mc_cl',
}
