import type { InputParamsList } from './_type';

const preset: InputParamsList = {
   aprilFools: { params: { enabled: true } },
   audio: { params: { enabled: false } },
   coverImage: { params: { enabled: true } },
   previewTime: { params: { enabled: true } },
   progression: {
      params: {
         enabled: false,
         'Expert+': false,
         ExpertPlus: false,
         Expert: false,
         Hard: false,
         Normal: false,
         Easy: false,
      },
   },
   zip: { params: { enabled: true } },
   acceptablePrec: { params: { enabled: true, prec: [8, 6] } },
   colorCheck: { params: { enabled: true } },
   doubleDirectional: { params: { enabled: true } },
   effectiveBPM: { params: { enabled: true, ebpmThres: 450, ebpmsThres: 350 } },
   excessiveDouble: { params: { enabled: true, threshold: 0.6 } },
   hitboxInline: { params: { enabled: true } },
   hitboxPath: { params: { enabled: true } },
   hitboxReverseStair: { params: { enabled: true } },
   hitboxStair: { params: { enabled: true } },
   improperArc: { params: { enabled: true } },
   improperChain: { params: { enabled: true } },
   improperWindow: { params: { enabled: true } },
   inlineAngle: { params: { enabled: true, maxTime: 0.25 } },
   oneSaber: { params: { enabled: true } },
   parity: { params: { enabled: true, warningThres: 90, errorThres: 45, allowedRot: 90 } },
   shradoAngle: { params: { enabled: true, distance: 1, maxTime: 0.4 } },
   slowSlider: { params: { enabled: true, minSpeed: 0.02 } },
   speedPause: { params: { enabled: false, maxTime: 0.075 } },
   stackedNote: { params: { enabled: true } },
   varySwing: { params: { enabled: true } },
   visionBlock: { params: { enabled: true, specific: 'time', minTime: 0.1, maxTime: 0.75 } },
   centerObstacle: { params: { enabled: true, recovery: 0.4 } },
   shortObstacle: { params: { enabled: true, minDur: 0.015 } },
   zeroObstacle: { params: { enabled: true } },
   insufficientLight: { params: { enabled: true } },
   invalidEventBox: { params: { enabled: true } },
   unlitBomb: { params: { enabled: true } },
   difficultyLabel: { params: { enabled: false } },
   hotStart: { params: { enabled: true, time: 1.5 } },
   invalidObject: { params: { enabled: true } },
   njs: { params: { enabled: true } },
   outsidePlayable: { params: { enabled: true } },
};

export default preset;
